
# iam-apiserver å…¨é…ç½?
# RESTful æœåŠ¡é…ç½®
server:
    mode: debug # server mode: release, debug, testï¼Œé»˜è®?release
    healthz: true # æ˜¯å¦å¼€å¯å¥åº·æ£€æŸ¥ï¼Œå¦‚æœå¼€å¯ä¼šå®‰è£… /healthz è·¯ç”±ï¼Œé»˜è®?true
    middlewares: recovery,logger,secure,nocache,cors,dump # åŠ è½½çš?gin ä¸­é—´ä»¶åˆ—è¡¨ï¼Œå¤šä¸ªä¸­é—´ä»¶ï¼Œé€—å·(,)éš”å¼€
    max-ping-count: 3 # http æœåŠ¡å¯åŠ¨åï¼Œè‡ªæ£€å°è¯•æ¬¡æ•°ï¼Œé»˜è®?3

# GRPC æœåŠ¡é…ç½®
grpc:
  bind-address: ${IAM_APISERVER_GRPC_BIND_ADDRESS} # grpc å®‰å…¨æ¨¡å¼çš?IP åœ°å€ï¼Œé»˜è®?0.0.0.0
  bind-port: ${IAM_APISERVER_GRPC_BIND_PORT} # grpc å®‰å…¨æ¨¡å¼çš„ç«¯å£å·ï¼Œé»˜è®?8081

# HTTP é…ç½®
insecure:
    bind-address: ${IAM_APISERVER_INSECURE_BIND_ADDRESS} # ç»‘å®šçš„ä¸å®‰å…¨ IP åœ°å€ï¼Œè®¾ç½®ä¸º 0.0.0.0 è¡¨ç¤ºä½¿ç”¨å…¨éƒ¨ç½‘ç»œæ¥å£ï¼Œé»˜è®¤ä¸º 127.0.0.1
    bind-port: ${IAM_APISERVER_INSECURE_BIND_PORT} # æä¾›éå®‰å…¨è®¤è¯çš„ç›‘å¬ç«¯å£ï¼Œé»˜è®¤ä¸º 8080

# HTTPS é…ç½®
secure:
    bind-address: ${IAM_APISERVER_SECURE_BIND_ADDRESS} # HTTPS å®‰å…¨æ¨¡å¼çš?IP åœ°å€ï¼Œé»˜è®¤ä¸º 0.0.0.0
    bind-port: ${IAM_APISERVER_SECURE_BIND_PORT} # ä½¿ç”¨ HTTPS å®‰å…¨æ¨¡å¼çš„ç«¯å£å·ï¼Œè®¾ç½®ä¸º 0 è¡¨ç¤ºä¸å¯ç”?HTTPSï¼Œé»˜è®¤ä¸º 8443
    tls:
        #cert-dir: .iam/cert # TLS è¯ä¹¦æ‰€åœ¨çš„ç›®å½•ï¼Œé»˜è®¤å€¼ä¸º /var/run/iam
        #pair-name: iam # TLS ç§é’¥å¯¹åç§°ï¼Œé»˜è®¤ iam
        cert-key:
            cert-file: ${IAM_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE} # åŒ…å« x509 è¯ä¹¦çš„æ–‡ä»¶è·¯å¾„ï¼Œç”?HTTPS è®¤è¯
            private-key-file: ${IAM_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE} # TLS ç§é’¥

# MySQL æ•°æ®åº“ç›¸å…³é…ç½?mysql:
  host: ${MARIADB_HOST} # MySQL æœºå™¨ ip å’Œç«¯å£ï¼Œé»˜è®¤ 127.0.0.1:3306
  username: ${MARIADB_USERNAME} # MySQL ç”¨æˆ·å?å»ºè®®æˆæƒæœ€å°æƒé™é›†)
  password: ${MARIADB_PASSWORD} # MySQL ç”¨æˆ·å¯†ç 
  database: ${MARIADB_DATABASE} # iam ç³»ç»Ÿæ‰€ç”¨çš„æ•°æ®åº“å
  max-idle-connections: 100 # MySQL æœ€å¤§ç©ºé—²è¿æ¥æ•°ï¼Œé»˜è®?100
  max-open-connections: 100 # MySQL æœ€å¤§æ‰“å¼€çš„è¿æ¥æ•°ï¼Œé»˜è®?100
  max-connection-life-time: 10s # ç©ºé—²è¿æ¥æœ€å¤§å­˜æ´»æ—¶é—´ï¼Œé»˜è®¤ 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

# Redis é…ç½®
redis:
  host: ${REDIS_HOST} # redis åœ°å€ï¼Œé»˜è®?127.0.0.1:6379
  port: ${REDIS_PORT} # redis ç«¯å£ï¼Œé»˜è®?6379
  password: ${REDIS_PASSWORD} # redis å¯†ç 
  #addrs:
  #master-name: # redis é›†ç¾¤ master åç§°
  #username: # redis ç™»å½•ç”¨æˆ·å?  #database: # redis æ•°æ®åº?  #optimisation-max-idle:  # redis è¿æ¥æ± ä¸­çš„æœ€å¤§ç©ºé—²è¿æ¥æ•°
  #optimisation-max-active: # æœ€å¤§æ´»è·ƒè¿æ¥æ•°
  #timeout: # è¿æ¥ redis æ—¶çš„è¶…æ—¶æ—¶é—´
  #enable-cluster: # æ˜¯å¦å¼€å¯é›†ç¾¤æ¨¡å¼?  #use-ssl: # æ˜¯å¦å¯ç”¨ TLS
  #ssl-insecure-skip-verify: # å½“è¿æ?redis æ—¶å…è®¸ä½¿ç”¨è‡ªç­¾åè¯ä¹¦

# JWT é…ç½®
jwt:
  realm: JWT # jwt æ ‡è¯†
  key: dfVpOK8LZeJLZHYmHdb1VdyRrACKpqoo # æœåŠ¡ç«¯å¯†é’?  timeout: 24h # token è¿‡æœŸæ—¶é—´(å°æ—¶)
  max-refresh: 24h # token æ›´æ–°æ—¶é—´(å°æ—¶)

log:
    name: apiserver # Loggerçš„åå­?    development: true # æ˜¯å¦æ˜¯å¼€å‘æ¨¡å¼ã€‚å¦‚æœæ˜¯å¼€å‘æ¨¡å¼ï¼Œä¼šå¯¹DPanicLevelè¿›è¡Œå †æ ˆè·Ÿè¸ªã€?    level: debug # æ—¥å¿—çº§åˆ«ï¼Œä¼˜å…ˆçº§ä»ä½åˆ°é«˜ä¾æ¬¡ä¸ºï¼šdebug, info, warn, error, dpanic, panic, fatalã€?    format: console # æ”¯æŒçš„æ—¥å¿—è¾“å‡ºæ ¼å¼ï¼Œç›®å‰æ”¯æŒconsoleå’Œjsonä¸¤ç§ã€‚consoleå…¶å®å°±æ˜¯textæ ¼å¼ã€?    enable-color: true # æ˜¯å¦å¼€å¯é¢œè‰²è¾“å‡ºï¼Œtrue:æ˜¯ï¼Œfalse:å?    disable-caller: false # æ˜¯å¦å¼€å?callerï¼Œå¦‚æœå¼€å¯ä¼šåœ¨æ—¥å¿—ä¸­æ˜¾ç¤ºè°ƒç”¨æ—¥å¿—æ‰€åœ¨çš„æ–‡ä»¶ã€å‡½æ•°å’Œè¡Œå·
    disable-stacktrace: false # æ˜¯å¦å†panicåŠä»¥ä¸Šçº§åˆ«ç¦æ­¢æ‰“å°å †æ ˆä¿¡æ?    output-paths: ${IAM_LOG_DIR}/iam-apiserver.log,stdout # æ”¯æŒè¾“å‡ºåˆ°å¤šä¸ªè¾“å‡ºï¼Œé€—å·åˆ†å¼€ã€‚æ”¯æŒè¾“å‡ºåˆ°æ ‡å‡†è¾“å‡ºï¼ˆstdoutï¼‰å’Œæ–‡ä»¶ã€?    error-output-paths: ${IAM_LOG_DIR}/iam-apiserver.error.log # zapå†…éƒ¨(éä¸šåŠ?é”™è¯¯æ—¥å¿—è¾“å‡ºè·¯å¾„ï¼Œå¤šä¸ªè¾“å‡ºï¼Œé€—å·åˆ†å¼€

feature:
  enable-metrics: true # å¼€å?metrics, router:  /metrics
  profiling: true # å¼€å¯æ€§èƒ½åˆ†æ, å¯ä»¥é€šè¿‡ <host>:<port>/debug/pprof/åœ°å€æŸ¥çœ‹ç¨‹åºæ ˆã€çº¿ç¨‹ç­‰ç³»ç»Ÿä¿¡æ¯ï¼Œé»˜è®¤å€¼ä¸º true
