
health-check-path: healthz # å¥åº·æ£€æŸ¥è·¯ç”±ï¼Œé»˜è®¤ä¸?/healthz
health-check-address: 0.0.0.0:5050 # å¥åº·æ£€æŸ¥ç»‘å®šåœ°å€ï¼Œé»˜è®¤ä¸º 0.0.0.0:5050

watcher:
  clean:
    max-reserve-days: 180 # æˆæƒå®¡è®¡æ—¥å¿—åœ¨MySQLä¸­æœ€å¤šä¿ç•™çš„å¤©æ•°ï¼Œè¶…è¿‡è¯¥å¤©æ•°åï¼Œæ—¥å¿—ä¼šè¢«åˆ é™¤ï¼ˆé»˜è®?80å¤©ï¼‰
  task:
    max-inactive-days: 180 # è´¦æˆ·æœ€å¤§ä¸ç™»å½•å¤©æ•°ï¼Œè¶…è¿‡è¯¥å¤©æ•°åè´¦æˆ·ä¼šè¢«ç¦æ­¢ç™»å½•ï¼ˆé»˜è®¤ä¸ç¦æ­¢ï¼‰

# MySQL æ•°æ®åº“ç›¸å…³é…ç½?mysql:
  host: ${MARIADB_HOST} # MySQL æœºå™¨ ip å’Œç«¯å£ï¼Œé»˜è®¤ 127.0.0.1:3306
  username: ${MARIADB_USERNAME} # MySQL ç”¨æˆ·å?å»ºè®®æˆæƒæœ€å°æƒé™é›†)
  password: ${MARIADB_PASSWORD} # MySQL ç”¨æˆ·å¯†ç 
  database: ${MARIADB_DATABASE} # iam ç³»ç»Ÿæ‰€ç”¨çš„æ•°æ®åº“å
  max-idle-connections: 100 # MySQL æœ€å¤§ç©ºé—²è¿æ¥æ•°ï¼Œé»˜è®?100
  max-open-connections: 100 # MySQL æœ€å¤§æ‰“å¼€çš„è¿æ¥æ•°ï¼Œé»˜è®?100
  max-connection-life-time: 10s # ç©ºé—²è¿æ¥æœ€å¤§å­˜æ´»æ—¶é—´ï¼Œé»˜è®¤ 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

# Redis é…ç½®
redis:
  host: ${REDIS_HOST} # redis åœ°å€ï¼Œé»˜è®?127.0.0.1:6379
  port: ${REDIS_PORT} # redis ç«¯å£ï¼Œé»˜è®?6379
  password: ${REDIS_PASSWORD} # redis å¯†ç 
  database: 1 # redis æ•°æ®åº?  optimisation-max-idle: 100  # redis è¿æ¥æ± ä¸­çš„æœ€å¤§ç©ºé—²è¿æ¥æ•°
  optimisation-max-active: 0 # æœ€å¤§æ´»è·ƒè¿æ¥æ•°
  enable-cluster: false # æ˜¯å¦å¼€å¯é›†ç¾¤æ¨¡å¼?  #addrs: 
  #master-name: # redis é›†ç¾¤ master åç§°
  #username: # redis ç™»é™†ç”¨æˆ·å?  #timeout: # è¿æ¥ redis æ—¶çš„è¶…æ—¶æ—¶é—´
  #use-ssl: # æ˜¯å¦å¯ç”¨ TLS
  #ssl-insecure-skip-verify: # å½“è¿æ?redis æ—¶å…è®¸ä½¿ç”¨è‡ªç­¾åè¯ä¹¦

log:    
    name: watcher
    development: true    
    level: debug # debug, info, warn, error, dpanic, panic, fatal    
    format: console # console, json    
    enable-color: true # æ˜¯å¦å¼€å¯é¢œè‰²è¾“å‡ºï¼Œtrue:æ˜¯ï¼Œfalse:å?   
    disable-caller: false # æ˜¯å¦å¼€å?callerï¼Œå¦‚æœå¼€å¯ä¼šåœ¨æ—¥å¿—ä¸­æ˜¾ç¤ºè°ƒç”¨æ—¥å¿—æ‰€åœ¨çš„æ–‡ä»¶ã€å‡½æ•°å’Œè¡Œå·    
    disable-stacktrace: false # æ˜¯å¦å†panicåŠä»¥ä¸Šçº§åˆ«ç¦æ­¢æ‰“å°å †æ ˆä¿¡æ?   
    output-paths: ${IAM_LOG_DIR}/iam-watcher.log,stdout # å¤šä¸ªè¾“å‡ºï¼Œé€—å·åˆ†å¼€ã€‚stdoutï¼šæ ‡å‡†è¾“å‡ºï¼Œ    
    error-output-paths: ${IAM_LOG_DIR}/iam-watcher.error.log # zapå†…éƒ¨(éä¸šåŠ?é”™è¯¯æ—¥å¿—è¾“å‡ºè·¯å¾„ï¼Œå¤šä¸ªè¾“å‡ºï¼Œé€—å·åˆ†å¼€  
