#

purge-delay: 10 # å®¡è®¡æ—¥å¿—æ¸…ç†æ—¶é—´é—´éš”ï¼Œé»˜è®?10s
health-check-path: healthz # å¥åº·æ£€æŸ¥è·¯ç”±ï¼Œé»˜è®¤ä¸?/healthz
health-check-address: 0.0.0.0:7070 # å¥åº·æ£€æŸ¥ç»‘å®šç«¯å£ï¼Œé»˜è®¤ä¸?0.0.0.0:7070
omit-detailed-recording: true # è®¾ç½®ä¸?true ä¼šè®°å½•è¯¦ç»†çš„æˆæƒå®¡è®¡æ—¥å¿—ï¼Œé»˜è®¤ä¸º false

# Redis é…ç½®
redis:
  host: ${REDIS_HOST} # redis åœ°å€ï¼Œé»˜è®?127.0.0.1:6379
  port: ${REDIS_PORT} # redis ç«¯å£ï¼Œé»˜è®?6379
  password: ${REDIS_PASSWORD} # redis å¯†ç 
  database: 0 # redis æ•°æ®åº?  optimisation-max-idle: 100  # redis è¿æ¥æ± ä¸­çš„æœ€å¤§ç©ºé—²è¿æ¥æ•°
  optimisation-max-active: 0 # æœ€å¤§æ´»è·ƒè¿æ¥æ•°
  enable-cluster: false # æ˜¯å¦å¼€å¯é›†ç¾¤æ¨¡å¼?  #addrs:
  #master-name: # redis é›†ç¾¤ master åç§°
  #username: # redis ç™»å½•ç”¨æˆ·å?  #timeout: # è¿æ¥ redis æ—¶çš„è¶…æ—¶æ—¶é—´
  #use-ssl: # æ˜¯å¦å¯ç”¨ TLS
  #ssl-insecure-skip-verify: # å½“è¿æ?redis æ—¶å…è®¸ä½¿ç”¨è‡ªç­¾åè¯ä¹¦

# pump é…ç½®
pumps:
  mongo:
    type: mongo # pump ç±»å‹
    meta:
      collection_name: ${IAM_PUMP_COLLECTION_NAME} # mongodb collection name
      mongo_url: ${IAM_PUMP_MONGO_URL} # mongodb url
      collection_cap_max_size_bytes: 1048576 # è®¾ç½®æœ€å¤§çš„capped collection
      collection_cap_enable: true

log:
    name: pump # Loggerçš„åå­?    development: true # æ˜¯å¦æ˜¯å¼€å‘æ¨¡å¼ã€‚å¦‚æœæ˜¯å¼€å‘æ¨¡å¼ï¼Œä¼šå¯¹DPanicLevelè¿›è¡Œå †æ ˆè·Ÿè¸ªã€?    level: debug # æ—¥å¿—çº§åˆ«ï¼Œä¼˜å…ˆçº§ä»ä½åˆ°é«˜ä¾æ¬¡ä¸ºï¼šdebug, info, warn, error, dpanic, panic, fatalã€?    format: console # æ”¯æŒçš„æ—¥å¿—è¾“å‡ºæ ¼å¼ï¼Œç›®å‰æ”¯æŒconsoleå’Œjsonä¸¤ç§ã€‚consoleå…¶å®å°±æ˜¯textæ ¼å¼ã€?    enable-color: true # æ˜¯å¦å¼€å¯é¢œè‰²è¾“å‡ºï¼Œtrue:æ˜¯ï¼Œfalse:å?    disable-caller: false # æ˜¯å¦å¼€å?callerï¼Œå¦‚æœå¼€å¯ä¼šåœ¨æ—¥å¿—ä¸­æ˜¾ç¤ºè°ƒç”¨æ—¥å¿—æ‰€åœ¨çš„æ–‡ä»¶ã€å‡½æ•°å’Œè¡Œå·
    disable-stacktrace: false # æ˜¯å¦å†panicåŠä»¥ä¸Šçº§åˆ«ç¦æ­¢æ‰“å°å †æ ˆä¿¡æ?    output-paths: ${IAM_LOG_DIR}/iam-pump.log,stdout # å¤šä¸ªè¾“å‡ºï¼Œé€—å·åˆ†å¼€ã€‚stdoutï¼šæ ‡å‡†è¾“å‡ºï¼Œ
    error-output-paths: ${IAM_LOG_DIR}/iam-pump.error.log # zapå†…éƒ¨(éä¸šåŠ?é”™è¯¯æ—¥å¿—è¾“å‡ºè·¯å¾„ï¼Œå¤šä¸ªè¾“å‡ºï¼Œé€—å·åˆ†å¼€
