
apiVersion: v1
user:
  #token: # JWT Token
  username: ${CONFIG_USER_USERNAME} # iam ç”¨æˆ·å?  password: ${CONFIG_USER_PASSWORD} # iam å¯†ç 
  #secret-id: # å¯†é’¥ ID
  #secret-key: # å¯†é’¥ Key
  client-certificate: ${CONFIG_USER_CLIENT_CERTIFICATE} # ç”¨äº TLS çš„å®¢æˆ·ç«¯è¯ä¹¦æ–‡ä»¶è·¯å¾„
  client-key: ${CONFIG_USER_CLIENT_KEY} # ç”¨äº TLS çš„å®¢æˆ·ç«¯ key æ–‡ä»¶è·¯å¾„
  #client-certificate-data:
  #client-key-data:

server:
  address: https://${CONFIG_SERVER_ADDRESS} # iam api-server åœ°å€
  timeout: 10s # è¯·æ±‚ api-server è¶…æ—¶æ—¶é—´
  #max-retries: # æœ€å¤§é‡è¯•æ¬¡æ•°ï¼Œé»˜è®¤ä¸?0
  #retry-interval: # é‡è¯•é—´éš”ï¼Œé»˜è®¤ä¸º 1s
  #tls-server-name: # TLS æœåŠ¡å™¨åç§?  #insecure-skip-tls-verify: # è®¾ç½®ä¸?true è¡¨ç¤ºè·³è¿‡ TLS å®‰å…¨éªŒè¯æ¨¡å¼ï¼Œå°†ä½¿å¾— HTTPS è¿æ¥ä¸å®‰å…?  certificate-authority: ${CONFIG_SERVER_CERTIFICATE_AUTHORITY} # ç”¨äº CA æˆæƒçš?cert æ–‡ä»¶è·¯å¾„
  #certificate-authority-data:
