
# Default values for iam.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

apiServer:
  name: iam-apiserver
  image:
    repository: ccr.ccs.tencentyun.com/lkccc/iam-apiserver-amd64
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.6.2"
  insecure:
    bindPort: 8080
  service:
    http:
      nodePort: 30080 # NodeèŠ‚ç‚¹çš„ç«¯å£ï¼Œ<nodeIP>:nodePort æ˜¯æä¾›ç»™é›†ç¾¤å¤–éƒ¨å®¢æˆ·è®¿é—®serviceçš„å…¥å?      port: 8080 # serviceæš´éœ²åœ¨cluster ipä¸Šçš„ç«¯å£ï¼Œé€šè¿‡<cluster ip>:portè®¿é—®æœåŠ¡,é€šè¿‡æ­¤ç«¯å£é›†ç¾¤å†…çš„æœåŠ¡å¯ä»¥ç›¸äº’è®¿é—?      targetPort: 8080 # Podçš„å¤–éƒ¨è®¿é—®ç«¯å£ï¼Œportå’ŒnodePortçš„æ•°æ®é€šè¿‡è¿™ä¸ªç«¯å£è¿›å…¥åˆ°Podå†…éƒ¨ï¼ŒPodé‡Œé¢çš„containersçš„ç«¯å£æ˜ å°„åˆ°è¿™ä¸ªç«¯å£ï¼Œæä¾›æœåŠ?    https:
      nodePort: 30443
      port: 8443
      targetPort: 8443
    rpc:
      nodePort: 30081
      port: 8081
      targetPort: 8081

authzServer:
  name: iam-authz-server
  image:
    repository: ccr.ccs.tencentyun.com/lkccc/iam-authz-server-amd64
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.6.2"
  insecure:
    bindPort: 9090
  service:
    http:
      nodePort: 31090 # NodeèŠ‚ç‚¹çš„ç«¯å£ï¼Œ<nodeIP>:nodePort æ˜¯æä¾›ç»™é›†ç¾¤å¤–éƒ¨å®¢æˆ·è®¿é—®serviceçš„å…¥å?      port: 9090 # serviceæš´éœ²åœ¨cluster ipä¸Šçš„ç«¯å£ï¼Œé€šè¿‡<cluster ip>:portè®¿é—®æœåŠ¡,é€šè¿‡æ­¤ç«¯å£é›†ç¾¤å†…çš„æœåŠ¡å¯ä»¥ç›¸äº’è®¿é—?      targetPort: 9090 # Podçš„å¤–éƒ¨è®¿é—®ç«¯å£ï¼Œportå’ŒnodePortçš„æ•°æ®é€šè¿‡è¿™ä¸ªç«¯å£è¿›å…¥åˆ°Podå†…éƒ¨ï¼ŒPodé‡Œé¢çš„containersçš„ç«¯å£æ˜ å°„åˆ°è¿™ä¸ªç«¯å£ï¼Œæä¾›æœåŠ?    https:
      nodePort: 31443
      port: 9443
      targetPort: 9443
pump:
  name: iam-pump
  image:
    repository: ccr.ccs.tencentyun.com/lkccc/iam-pump-amd64
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.6.2"
  healthPort: 7070
  service:
    http:
      nodePort: 30070 # NodeèŠ‚ç‚¹çš„ç«¯å£ï¼Œ<nodeIP>:nodePort æ˜¯æä¾›ç»™é›†ç¾¤å¤–éƒ¨å®¢æˆ·è®¿é—®serviceçš„å…¥å?      port: 7070 # serviceæš´éœ²åœ¨cluster ipä¸Šçš„ç«¯å£ï¼Œé€šè¿‡<cluster ip>:portè®¿é—®æœåŠ¡,é€šè¿‡æ­¤ç«¯å£é›†ç¾¤å†…çš„æœåŠ¡å¯ä»¥ç›¸äº’è®¿é—?      targetPort: 7070 # Podçš„å¤–éƒ¨è®¿é—®ç«¯å£ï¼Œportå’ŒnodePortçš„æ•°æ®é€šè¿‡è¿™ä¸ªç«¯å£è¿›å…¥åˆ°Podå†…éƒ¨ï¼ŒPodé‡Œé¢çš„containersçš„ç«¯å£æ˜ å°„åˆ°è¿™ä¸ªç«¯å£ï¼Œæä¾›æœåŠ?
watcher:
  name: iam-watcher
  image:
    repository: ccr.ccs.tencentyun.com/lkccc/iam-watcher-amd64
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.6.2"
  healthPort: 5050
  service:
    http:
      nodePort: 30050 # NodeèŠ‚ç‚¹çš„ç«¯å£ï¼Œ<nodeIP>:nodePort æ˜¯æä¾›ç»™é›†ç¾¤å¤–éƒ¨å®¢æˆ·è®¿é—®serviceçš„å…¥å?      port: 5050 # serviceæš´éœ²åœ¨cluster ipä¸Šçš„ç«¯å£ï¼Œé€šè¿‡<cluster ip>:portè®¿é—®æœåŠ¡,é€šè¿‡æ­¤ç«¯å£é›†ç¾¤å†…çš„æœåŠ¡å¯ä»¥ç›¸äº’è®¿é—?      targetPort: 5050 # Podçš„å¤–éƒ¨è®¿é—®ç«¯å£ï¼Œportå’ŒnodePortçš„æ•°æ®é€šè¿‡è¿™ä¸ªç«¯å£è¿›å…¥åˆ°Podå†…éƒ¨ï¼ŒPodé‡Œé¢çš„containersçš„ç«¯å£æ˜ å°„åˆ°è¿™ä¸ªç«¯å£ï¼Œæä¾›æœåŠ?
iamctl:
  name: iamctl
  image:
    repository: ccr.ccs.tencentyun.com/lkccc/iamctl-amd64
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.6.2"

image:
  pullPolicy: Always

imagePullSecrets:
  - name: "ccr-registry"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

serviceType: NodePort

resources: 
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 512Mi

livenessProbe:
  failureThreshold: 1
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3

readinessProbe:
  failureThreshold: 1
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3

startupProbe:
  failureThreshold: 10
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
